### ISSUE TITLE
Is this possible?

### ISSUE THREAD

**Issue by TajuModding** [fransallen/thedev.id#113]
Can i create a subdomain of my subdomain

so i wanted to create a subdomain of `op.thedev.id`

like `foo.op.thedev.id` or `boo.op.thedev.id`

**Comment by fransallen** [comment]
Not at this point, because that would just be too complex. I'm also not sure I can provide it in future features either.

I believe it would be very useful if questions like this were placed on the [Discussions](https://github.com/fransallen/thedev.id/discussions) tab. Feel free to ask questions there :)
