### ISSUE TITLE
Is the project dead? no pull requests are getting merged.

### ISSUE THREAD

**Issue by legendlife** [fransallen/thedev.id#336]
No pull requests are getting merged since 6 months. Is this project dead? If so why not archive it? It was a cool project it's a shame it's getting ended but do check those pull requests and if you are unable to continue, Please archive it. @fransallen

**Comment by QwertyIsCoding** [comment]
I agree that the project is kind of slow but I think they are just not being able to handle these many users... I'm pretty sure they will figure out a way sooner or later in the future and yeah! 

Guess what, even one of my PRs got closed but it was the wrong one... I haven't gotten any responses about it yet but it says all the checks are done and is ready to merge... It is just that it isn't being merged... 

Let's just hope this project springs back to life cause this project is just so cool!

For now I'm using is-a.dev because it was the first one I say and is amazing and that is the domain I am using for my personal website but I want one for my other project and this domain would be great! 

Also, this might just be the longest comment I have ever written 😂

**Comment by legendlife** [comment]
I also hope so, it becomes active. It's a cool project not gonna lie

**Comment by QwertyIsCoding** [comment]
> I also hope so, it becomes active. It's a cool project not gonna lie

Yeah, and to be honest, the fact that it is free is awesome so I guess it is just a drawback of the project if you know what I mean.

**Comment by legendlife** [comment]
> > I also hope so, it becomes active. It's a cool project not gonna lie
> 
> Yeah, and to be honest, the fact that it is free is awesome so I guess it is just a drawback of the project if you know what I mean.

Yeah I feel ya

**Comment by fransallen** [comment]
Sorry for the delay, everyone. Currently working on it now :)
